name: Build vcs-build-container
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Docker tags
        id: metabase
        uses: docker/metadata-action@v3
        with:
          images:
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=schedule,pattern=base-{{date 'YYYYMMDD'}}
            type=raw,value=base

      - name: Build and push base container
        uses: docker/build-push-action@v2
        with:
          context: ./base
          file: ./base/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metabase.outputs.tags }}
          labels: ${{ steps.metabase.outputs.labels }}
